[package]
name = "prime"
version = "0.1.0"
authors = ["Whitedwarf137 <whitedwarf137@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitset = { path = "../bitset" }